# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build hunt-x`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t hunt-x`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system hunt-x && \
          adduser --system -G hunt-x hunt-x

COPY dist/hunt-x hunt-x/
RUN chown -R hunt-x:hunt-x .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix hunt-x --omit=dev -f install

CMD [ "node", "hunt-x" ]
