/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * @fileoverview Defines the IApplication interface for application data.
 * @version 1.0.0
 * @module applicationInterface
 */

import { Optional } from 'sequelize';
import { ApplicationStatus } from '../types';

/**
 * Interface representing the attributes of an application.
 */
interface IApplication {
  [x: string]: any;
  id?: number;
  jobId: number;
  candidateId: number;
  status?: ApplicationStatus;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Interface for creating a new application (excluding autogenerated fields).
 */
type IApplicationCreation = Optional<
  IApplication,
  'id' | 'status' | 'createdAt' | 'updatedAt'
>;

/**
 * @fileoverview
 * @version
 * @module
 */

interface IApplicationsQuery {
  jobId?: number;
  candidateId?: number;
  status?: string;
}

interface IApplicationQuery {
  applicationId?: number;
  candidateId?: number;
  jobId?: number;
}

export {
  IApplication,
  IApplicationCreation,
  IApplicationsQuery,
  IApplicationQuery,
};
