/**
 * @fileoverview Defines the IJob interface for job data.
 * @version 1.0.0
 * @module jobInterface
 */

import { Optional } from 'sequelize';

/**
 * Interface representing the attributes of a job.
 */
interface IJob {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  [x: string]: any;
  id?: number;
  title: string;
  description: string;
  responsibility: string;
  requirements: string[];
  benefits?: string[];
  location: string;
  type: 'Full-time' | 'Part-time' | 'Contract' | 'Freelance' | 'Internship';
  vacancy?: number;
  deadline: Date;
  tags: string[];
  recruiterId?: number;
  views?: number;
  isActive?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

interface IJobQuery {
  title?: string;
  location?: string;
  type?: string[];
  tags?: string[];
  isActive?: boolean;
  page?: number;
  pageSize?: number;
  createdAt?: Date;
}

/**
 * Interface for creating a new job (excluding autogenerated fields).
 */
type IJobCreation = Optional<
  IJob,
  | 'id'
  | 'benefits'
  | 'vacancy'
  | 'views'
  | 'isActive'
  | 'createdAt'
  | 'updatedAt'
>;

export { IJob, IJobQuery, IJobCreation };
