/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * @fileoverview Defines the ICompany interface for company data.
 * @version 1.0.0
 * @module companyInterface
 */

import { Optional } from 'sequelize';

/**
 * Interface representing the attributes of a company.
 */
interface IRecruiter {
  [x: string]: any;
  id?: number;
  name?: string;
  industry?: string;
  websiteUrl?: string;
  location?: string;
  description?: string;
  size?: number;
  foundedIn?: number;
  isVerified?: boolean;
  userId?: number;
  createdAt?: Date;
  updatedAt?: Date;
}

/**
 * Interface for creating a new company (excluding autogenerated fields).
 */
type IRecruiterCreation = Optional<
  IRecruiter,
  'id' | 'createdAt' | 'updatedAt'
>;

interface IRecruiterQuery {
  id?: number;
  userId?: number;
}

interface IRecruitersQuery {
  name?: string;
  industry?: string;
  location?: string;
  isVerified?: boolean;
}

export { IRecruiter, IRecruiterCreation, IRecruiterQuery, IRecruitersQuery };
