/**
 * @fileoverview Defines the IUser interface for user data.
 * @version 1.0.0
 * @module userInterface
 */

import { Optional } from 'sequelize';

/**
 * Interface representing the attributes of a user.
 */
interface IUser {
  id?: number;
  avatarUrl?: string;
  email: string;
  mobileNumber: string;
  password: string;
  role?: 'candidate' | 'recruiter';
  isVerified?: boolean;
  createdAt?: Date;
  updatedAt?: Date;
}

interface IUserQuery {
  id?: number;
  email?: string;
}

interface IUpdateContactQuery {
  email?: string;
  phoneNumber?: string;
}

interface IUpdatePasswordQuery {
  currentPassword?: string;
  newPassword?: string;
  confirmPassword?: string;
}

/**
 * Interface for creating a new user (excluding autogenerated fields).
 */
type IUserCreation = Optional<IUser, 'id' | 'createdAt' | 'updatedAt'>;

export {
  IUser,
  IUserQuery,
  IUpdateContactQuery,
  IUpdatePasswordQuery,
  IUserCreation,
};
